### ISSUE TITLE
Unable to figure out how to apply my gpu configuration to immich

### ISSUE THREAD

**Issue by nerddotdad** [nerddotdad/truecharts#276]
Currently have the following code commented out in my helm-release.yaml for immich. This lives under the values section of the chart.

```yaml

    workload:
      main:
        podSpec:
          runtimeClassName: "nvidia"
          containers:
            micros:
              resources:
                limits:
                  nvidia.com/gpu: 1

```
